# Site settings
title:          YoungHo's Blog
description:    "Private blog for Youngho"
baseurl:        # the subpath of your site, e.g. "/blog"
url:            "https://chesterhow.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         YoungHo Jeon
  url:          https://chester.how
  email:        yhjun1000@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

theme: tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
comments: true

#links:
#    - label: "Email"
#      icon: "fas fa-fw fa-envelope-square"
#      url: "mailto:yhjun1000@gmail.com"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/jeonyoungho"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://www.instagram.com/jyho_o"
#    - label: "Facebook"
#      icon: "fab fa-fw fa-facebook-square"
#      url: "https://www.facebook.com/profile.php?id=100004766491505"
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      # url: "https://your-website.com"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      # url: "https://twitter.com/"